Fix test suite instability
Tradeshift/io pull request #70
Opened 2020-09-24 15:18 UTC by wejendorp

Attempting to fix the test instability with IE11.

2020-09-24 17:07 UTC, wejendorp commented
Omg I think I finally got it to be not flaky!

2020-09-24 18:03 UTC, esmailpour-hosein requested changes
Nice job! LGTM but there are couple of things, 
First please also update the README file: https://github.com/Tradeshift/io/blame/master/README.md#L194
Second, this is a breaking change IMO and we should bump major version, based on my search with livegrep Chrome is the only place using it, and it would be, hopefully, an easy update 👍

2020-09-25 07:26 UTC, esmailpour-hosein approved these changes

2020-09-25 07:28 UTC, merged

2020-09-25 07:32 UTC, tradeshiftcicomponents commented
:tada: This PR is included in version 4.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tradeshift/io)
- [GitHub release](https://github.com/Tradeshift/io/releases/tag/v4.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: